server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    mode: HTML5
  servlet:
    multipart:
      max-file-size: 5MB
dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://192.168.5.129:2181
  consumer:
    check: false
    timeout: 1000
fdfs:
  #读取的时间
  so-timeout: 1000
  #上传的图片的缩略图大小
  thumb-image:
    height: 200
    width: 200
  pool:
    jmx-enabled: false
  #追踪器的列表，如果列表有多个，在下面接着写就可以，比如：- xxxx
  tracker-list:
    - 192.168.5.129:22122
#图片回显自定义路径
image:
  path: http://192.168.5.129/
